# Deploy bitnami/Keycloak via helm as a Loadbalancer service
- name: Install Keycloak via Helm
  community.kubernetes.helm:
    name: keycloak
    chart_ref: bitnami/keycloak
    release_namespace: keycloak
    create_namespace: true
    kubeconfig: "{{ kubeconfig }}"
    values:
      service:
        type: LoadBalancer
      auth:
        adminUser: admin
        adminPassword: "{{ keycloak_admin_password }}"
      postgresql:
        enabled: false
      externalDatabase:
        host: postgres-postgresql.keycloak.svc.cluster.local
        user: "{{ postgres_user }}"
        password: "{{ postgres_pass }}"
        database: "{{ postgres_db }}"
